# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        # stages: [push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy
        exclude: build_helpers
        additional_dependencies:
          - types-cachetools==5.0.1
          - types-filelock==3.2.5
          - types-requests==2.27.25
          - types-tabulate==0.8.9
          - types-python-dateutil==2.8.15
        # stages: [push]

  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        name: isort (python)
        # stages: [push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                tests/.*|
                .*\.svg
            )$
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-ast
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .*\.md
            )$

  - repo: https://github.com/pycqa/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        args: [-c, "pyproject.toml"]
        exclude: |
            (?x)^(
                tests/.*
            )$
        additional_dependencies: [toml]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: tests
  #       entry: pytest
  #       args: [-x, --ff, --random-order, --cov=coingro, --cov-config=.coveragerc, tests/]
  #       types: [python]
  #       language: system
  #       pass_filenames: false
  #       always_run: true
